DROP TABLE IF EXISTS t_comments;
DROP TABLE IF EXISTS t_posts;
DROP TABLE IF EXISTS t_users_roles;
DROP TABLE IF EXISTS t_client;
DROP TABLE IF EXISTS t_admin;
DROP TABLE IF EXISTS t_roles;
DROP TABLE IF EXISTS t_users;
